# Generated by Django 4.1.6 on 2023-02-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lcapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apply",
            old_name="acompany",
            new_name="ap_acompany",
        ),
        migrations.RenameField(
            model_name="apply",
            old_name="resume",
            new_name="ap_resume",
        ),
        migrations.RenameField(
            model_name="apply",
            old_name="aseeker",
            new_name="ap_seeker",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="affiliate",
            new_name="co_affiliate",
        ),
        migrations.RemoveField(
            model_name="company",
            name="career",
        ),
        migrations.RemoveField(
            model_name="company",
            name="edate",
        ),
        migrations.RemoveField(
            model_name="company",
            name="prefer",
        ),
        migrations.RemoveField(
            model_name="company",
            name="sdate",
        ),
        migrations.RemoveField(
            model_name="company",
            name="sector",
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("re_sector", models.CharField(max_length=45)),
                ("re_career", models.CharField(max_length=20)),
                ("re_prefer", models.TextField()),
                ("re_sdate", models.DateField()),
                ("re_edate", models.DateField()),
                (
                    "re_affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lcapp.seeker"
                    ),
                ),
            ],
        ),
    ]
