# Generated by Django 4.1.6 on 2023-02-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lcapp", "0002_rename_acompany_apply_ap_acompany_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="re_affiliate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lcapp.company"
            ),
        ),
    ]
