# Generated by Django 4.1.6 on 2023-02-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lcapp", "0003_alter_recruitment_re_affiliate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="ap_acompany",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lcapp.recruitment"
            ),
        ),
    ]
