# Generated by Django 4.1.6 on 2023-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lcapp", "0004_alter_apply_ap_acompany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apply",
            name="ap_resume",
            field=models.FileField(blank=True, upload_to="%Y_%m_%d/"),
        ),
    ]
