# Generated by Django 4.1.6 on 2023-02-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lcapp", "0005_alter_apply_ap_resume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apply",
            old_name="ap_acompany",
            new_name="ap_recruitment",
        ),
    ]
